In [1]:
import numpy as np
dataset_filename = "Cha1_affinity_dataset.txt"  
# 横向是每一条数据包含的商品，，竖着看每一列代表一种商品。
# 分别是面包、牛奶、奶酪、苹果、香蕉。
X = np.loadtxt(dataset_filename)

In [2]:
print(X[:5])

[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


* 支持度：衡量的是给定规则应验的比例
* 置信度：衡量的是规则准确率如何，即符合给定条件的所有规则里，跟当前规则结论一致的比例有多少


###### 计算方法为首先统计当前规则的出现次数，再用它来除以条件相同的规则数量


In [ ]:
""""""

通过如下代码，通过判断交易数据中sample[3]的值，就能知道一个顾客是否买了苹果。

In [3]:
# First, how many rows contain our premiss: that a person is buying apples
num_apple_purchases = 0 
for sample in X:
    if sample[3] == 1:  # This person bought Apples
        num_apple_purchases += 1 
print("{0} people bought Apples.".format(num_apple_purchases))

36 people bought Apples.
