In [2]:
# 首先导入numpy库
import numpy as np

# 创建ndarray数组的方式有很多种

# Method1：基于list或turple

# 一维数组

# 基于list
arr1 = np.array([1, 2, 3, 4])
print(arr1)
# [1 2 3 4]

# 基于turple
arr_tuple = np.array((1, 2, 3, 4))
print(arr_tuple)
# [1 2 3 4]


# 二维数组(2*3)
arr2 = np.array([[1, 2, 4], [3, 4, 5]])
print(arr2)
# [[1 2 4]
#  [3 4 5]]


# 请注意：
# • 一维数组用print输出的时候为[1234]，跟python的列表是有些差异的，没有“,”
# • 在创建二维数组时，在每个子list外面还有一个“[]”，形式为“[[list1], [list2]]”



[1 2 3 4]
[1 2 3 4]
[[1 2 4]
 [3 4 5]]


In [4]:
import numpy as np
# Method2：基于np.arange

# 一维数组
arr1 = np.arange(5)
print(arr1)

# 二维数组
arr2 = np.array([np.arange(3), np.arange(3)])
arr2
print(arr2)


[0 1 2 3 4]
[[0 1 2]
 [0 1 2]]


In [6]:
import numpy as np
# Method3：基于arange以及reshape创建多维数组

# 创建三维数组
arr = np.arange(24).reshape(2, 3, 4)  # 二维三行四列
print(arr)

• 请注意：arange的⻓度与ndarray的维度的乘积要相等，即24=2X3X4 
• 用numpy.random创建数组的方法，可以参考我的文章:《为什么你用不好Numpy的random函数》 
• 其他创建ndarray的方法，各位小伙伴们自己可以研究下。

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
