• dtype属性，ndarray数组的数据类型，数据类型的种类，前面已描述。 

In [2]:
import numpy as np
np.arange(4, dtype=float)

array([0., 1., 2., 3.])

In [3]:
# 'D'表示复数类型
import numpy as np
np.arange(4, dtype='D')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
import numpy
numpy.array([1.22, 3.45, 6.779], dtype='int8')

array([1, 3, 6], dtype=int8)

• ndim属性，数组维度的数量 

In [6]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.ndim

2

• shape属性，数组对象的尺度，对于矩阵，即n行m列,shape是一个元组（tuple） 

In [7]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.shape

(2, 3)

• size属性用来保存元素的数量，相当于shape中nXm的值 

In [8]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.size

6

• itemsize属性返回数组中各个元素所占用的字节数大小。 

In [9]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.itemsize

4

• nbytes属性，如果想知道整个数组所需的字节数量，可以使用nbytes属性。其值等于数组的size属性值 乘以itemsize属性值。 

In [12]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.nbytes

24

In [14]:
import numpy
a = numpy.array([[1, 2, 3], [7, 8, 9]])
a.size * a.itemsize

24

• T属性，数组转置

In [18]:
import numpy as np
b = np.arange(24).reshape(4, 6)
print(b)
print()
print(b.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


• 复数的实部和虚部属性，real和imag属性 

In [19]:
import numpy as np
d = np.array([1.2+2j, 2+3j])
print(d)

[1.2+2.j 2. +3.j]


real属性返回数组的实部

In [20]:
import numpy as np
d = np.array([1.2+2j, 2+3j])
d.real

array([1.2, 2. ])

imag属性返回数组的虚部

In [22]:
import numpy as np
d = np.array([1.2+2j, 2+3j])
print(d.imag)

[2. 3.]


• flat属性，返回一个numpy.flatiter对象，即可迭代的对象。 

In [26]:
import numpy as np
e = np.arange(6).reshape(2, 3)
print(e)
f = e.flat
print(f)
for item in f:
    print(item)

[[0 1 2]
 [3 4 5]]
0
1
2
3
4
5


可通过位置进行索引，如下：

In [29]:
import numpy as np
e = np.arange(6).reshape(2, 3)
f = e.flat
print(f[2])
print(f[[1, 4]])

2
[1 4]


也可以进行赋值

In [33]:
import numpy as np
e = np.arange(6).reshape(2, 3)
e.flat = 7
print(e, "1")
e.flat[[1, 4]] = 1 
print(e, "2")

[[7 7 7]
 [7 7 7]] 1
[[7 1 7]
 [7 1 7]] 2
