• 一维数组 
一维数组的切片和索引与python的list索引类似。 

In [6]:
import numpy as np
a = np.arange(7)
print("a:\t", a)
print("a[1:4]:\t", a[1:4])
# 每间隔2个取一个数
print("a[:6:2]\t", a[:6:2])

a:	 [0 1 2 3 4 5 6]
a[1:4]:	 [1 2 3]
a[:6:2]	 [0 2 4]


• 二维数组的切片和索引

In [12]:
import numpy as np
b = np.arange(12).reshape(3, 4)
print(b, "\tb")
print(b[0:3,0:2], "\tb[0:3,0:2]")  # 前三行，前两列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 	b
[[0 1]
 [4 5]
 [8 9]] 	b[0:3,0:2]
