## 1、形状转换

• reshape()和resize() 

In [6]:
import numpy as np
b = np.arange(12).reshape(3, 4)
print(b.reshape(4, 3), "\tb.reshape(4, 3)")
print(b, "\tb")


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 	b.reshape(4, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 	b


In [7]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b.resize(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

函数resize（）的作用跟reshape（）类似，但是会改变所作用的数组，  
相当于有inplace=True的效果   
• ravel()和flatten()，将多维数组转换成一维数组，如下： 

In [14]:
import numpy as np
b = np.arange(12).reshape(3, 4)
print("b.ravel():\t", b.ravel())
print("b.flatten():\t", b.flatten())
print(b, "\tb")

b.ravel():	 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b.flatten():	 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 	b


    两者的区别在于返回拷⻉（copy）还是返回视图（view） ，flatten()返回一份拷⻉，需要分配新的内存空间， 对拷⻉所做的修改不会影响原始矩阵，而ravel()返回的是视图（view），会影响原始矩阵。
    参考如下代码：

In [15]:
# flatten()返回的是拷贝，不影响原始数组
# 即数组 "b" 没有发生变化
b.flatten()[2] = 20
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# ravel()返回的是视图，会影响原始数组
# 即数组 "b" 会发生变化
b.ravel()[2] = 20 
print(b)

[[ 0  1 20  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


• 用tuple指定数组的形状，如下： 

In [17]:
b.shape = (2, 6)
print(b)

[[ 0  1 20  3  4  5]
 [ 6  7  8  9 10 11]]


• 转置 
前面描述了数组转置的属性（T），也可以通过transpose()函数来实现 

In [18]:
b.transpose()

array([[ 0,  6],
       [ 1,  7],
       [20,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

## 2、堆叠数组

In [19]:
b

array([[ 0,  1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
c = b*2
c

array([[ 0,  2, 40,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

• 水平叠加 
hstack() 

In [23]:
np.hstack((b,c))

array([[ 0,  1, 20,  3,  4,  5,  0,  2, 40,  6,  8, 10],
       [ 6,  7,  8,  9, 10, 11, 12, 14, 16, 18, 20, 22]])

column_stack()函数以列方式对数组进行叠加，功能类似hstack（） 

In [24]:
np.column_stack((b,c))

array([[ 0,  1, 20,  3,  4,  5,  0,  2, 40,  6,  8, 10],
       [ 6,  7,  8,  9, 10, 11, 12, 14, 16, 18, 20, 22]])

• 垂直叠加 
vstack() 

In [25]:
np.vstack((b,c))

array([[ 0,  1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  2, 40,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

row_stack()函数以行方式对数组进行叠加，功能类似vstack（） 

In [26]:
np.row_stack((b,c))

array([[ 0,  1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  2, 40,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

• concatenate()方法，通过设置axis的值来设置叠加方向 
axis=1时，沿水平方向叠加 
axis=0时，沿垂直方向叠加 

In [27]:
np.concatenate((b,c),axis=1)

array([[ 0,  1, 20,  3,  4,  5,  0,  2, 40,  6,  8, 10],
       [ 6,  7,  8,  9, 10, 11, 12, 14, 16, 18, 20, 22]])

In [28]:
np.concatenate((b,c),axis=0)

array([[ 0,  1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  2, 40,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

axis=1的方向为列方向
axis=0的方向为行方向

____  |  col1    col2    col3    col4    col5  
row1  |  ____    ____    ____    ____    ____  
row2  |  ____    ____    ____    ____    ____     
row3  |  ____    ____    ____    ____    ____  
row4  |  ____    ____    ____    ____    ____  
row5  |  ____    ____    ____    ____    ____  



深度叠加 
这个有点烧脑，举个例子如下，自己可以体会下： 

In [29]:
arr_dstack = np.dstack((b,c))
print(arr_dstack.shape)
arr_dstack

(2, 6, 2)


array([[[ 0,  0],
        [ 1,  2],
        [20, 40],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [10, 20],
        [11, 22]]])

叠加前，b和c均是shape为(2,6)的二维数组，叠加后，arr_dstack是shape为(2,6,2)的三维数组。


## 3、数组的拆分
跟数组的叠加类似，数组的拆分可以分为横向拆分、纵向拆分以及深度拆分。涉及的的函数为hsplit()、 vsplit()、dsplit()以及split() 

In [30]:
b

array([[ 0,  1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

• 沿横向轴拆分（axis=1） 

In [31]:
np.hsplit(b, 2)

[array([[ 0,  1, 20],
        [ 6,  7,  8]]), array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [32]:
np.split(b, 2, axis=1)

[array([[ 0,  1, 20],
        [ 6,  7,  8]]), array([[ 3,  4,  5],
        [ 9, 10, 11]])]

• 沿纵向轴拆分（axis=0）

In [33]:
np.vsplit(b, 2)

[array([[ 0,  1, 20,  3,  4,  5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [34]:
np.split(b, 2, axis=0)

[array([[ 0,  1, 20,  3,  4,  5]]), array([[ 6,  7,  8,  9, 10, 11]])]

• 深度拆分 

In [35]:
arr_dstack

array([[[ 0,  0],
        [ 1,  2],
        [20, 40],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [10, 20],
        [11, 22]]])

In [36]:
np.dsplit(arr_dstack, 2)

[array([[[ 0],
         [ 1],
         [20],
         [ 3],
         [ 4],
         [ 5]],
 
        [[ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]]]), array([[[ 0],
         [ 2],
         [40],
         [ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16],
         [18],
         [20],
         [22]]])]

拆分的结果是原来的三维数组拆分成两个二维数组。