• 数组转换成list，使用tolist() 

In [4]:
import numpy as np
b = np.arange(12).reshape(3, 4)
print(b)
b.tolist()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

• 转换成指定类型，astype()函数 

In [5]:
b.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])