常用的函数如下,请注意函数在使用时需要指定axis轴的方向，若不指定，默认统计整个数组。 
• np.sum()，返回求和 
• np.mean()，返回均值 
• np.max()，返回最大值 
• np.min()，返回最小值 
• np.ptp()，数组沿指定轴返回最大值减去最小值，即（max-min） 
• np.std()，返回标准偏差（standarddeviation） 
• np.var()，返回方差（variance） 
• np.cumsum()，返回累加值 
• np.cumprod()，返回累乘积值

In [3]:
import numpy as np
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
print("最大值：\t\t\t", np.max(b))
print("沿axis=1轴方向统计：\t", np.max(b, axis=1))
print("沿axis=0轴方向统计：\t", np.max(b, axis=0))
print("最小值：\t\t\t", np.min(b))

最大值：			 11
沿axis=1轴方向统计：	 [ 3  7 11]
沿axis=0轴方向统计：	 [ 8  9 10 11]
最小值：			 0


• np.ptp()，返回整个数组的最大值减去最小值，如下： 

In [12]:
np.ptp(b)

11

In [13]:
# 沿axis=0轴方向
np.ptp(b, axis=0)

array([8, 8, 8, 8])

In [14]:
# 沿axis=1轴方向
np.ptp(b, axis=1)

array([3, 3, 3])

• np.cumsum()，沿指定轴方向进行累加

In [15]:
b.resize(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.cumsum(b, axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]], dtype=int32)

In [17]:
np.cumsum(b, axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]], dtype=int32)

• np.cumprod()，沿指定轴方向进行累乘积（Returnthecumulativeproductoftheelementsalong thegivenaxis） 

In [19]:
np.cumprod(b, axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336],
       [  9,  90, 990]], dtype=int32)

In [20]:
np.cumprod(b, axis=0)

array([[  0,   1,   2],
       [  0,   4,  10],
       [  0,  28,  80],
       [  0, 280, 880]], dtype=int32)