In [7]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [8]:
print(X[:5])


[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


In [10]:
# First , how many rows contain our premise : that a person is buying apples
num_people_purchases = 0
for sample in X:
    if sample[3] == 1:  # This person bought Apples
        num_people_purchases += 1
print("{0} people bought Apples.".format(num_people_purchases))

36 people bought Apples.


In [ ]:
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurances = defaultdict(int)
for sample in X:
    for premise in range(4):
        if sample[premise] == 0: continue
        num_occurances[premise] += 1
        for conclusion in range(n_featu)
        